GET http://localhost:8080/api/song/2
Accept: application/json

###

POST http://localhost:8080/api/song
Content-Type: application/json

{
  "title": "Bye Bye Love",
  "artist": "The Everly Brothers",
  "year": 1957
}

###

PUT http://localhost:8080/api/song
Content-Type: application/json

{
  "id": 3,
  "title": "Bye Bye Love",
  "artist": "The Everly Brothers",
  "year": 1958
}

###

DELETE http://localhost:8080/api/song/2
Accept: application/json

###
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded

{
  "grant_type": "password",
  "username": "JohnDoe",
  "password": "1111"
}